### ISSUE TITLE
broken link to rdflib in README

### ISSUE THREAD

**Issue by jonassmedegaard** [solid/solid-rest#57]
README.md contains this:
```markdown
Solid-Rest is included automatically in [rdflib]() when a script is run outside a browser.
```

...but there is no definition for `[rdflib]`  elsewhere in the file, so the link is broken.

**Comment by jeff-zucker** [comment]
Thank you for finding this for two reasons - the broken link and the fact that [rdflib](https://github.com/linkeddata/rdflib.js) changed the way it operates so this is no longer true.  I'll update the README to explain this.  Also, if you are operating in a nodejs environment, it is best to use solid-rest via [solid-node-client](https://github.com/solid/solid-node-client) and its documentation is more up to date.But  the short answer is this is how you use solid-rest with rdflib : 
```javascript
import * as $rdf from 'rdflib';                                                \
import SolidRest from 'solid-rest';                                                    
const client = new SolidRest()                                                  
const store = $rdf.graph();                                                     
const fetcher = $rdf.fetcher(store,{fetch:client.fetch.bind(client)});          
/**                                                                             
  from here on out, all fetches and updates from rdflib will use solid-rest     
 */
```
